"""Constants for the BTicino CLASSE100X integration."""

DOMAIN = "bticino_classe100x"

CONF_AUTH_METHOD = "auth_method"
CONF_SSH_KEY_PATH = "ssh_key_path"
CONF_PASSWORD = "password"
CONF_COMMAND_TIMEOUT = "command_timeout"
CONF_RELEASE_DELAY = "release_delay"

AUTH_METHOD_SSH_KEY = "ssh_key"
AUTH_METHOD_PASSWORD = "password"

DEFAULT_USERNAME = "root2"
DEFAULT_SSH_KEY_PATH = "/config/ssh/bticinokey"
DEFAULT_COMMAND_TIMEOUT = 10
DEFAULT_RELEASE_DELAY = 1.0

SSH_PORT = 22
OPENWEBNET_LOCAL_HOST = "0"
OPENWEBNET_PORT = 30006

BUTTON_TYPE_COMMAND = "command"
BUTTON_TYPE_TEST = "test"

OPENWEBNET_TEST_COMMAND = "*#*1##"

CONDOMINIUM_GATE_PRESS_COMMAND = "*8*19*20##"
CONDOMINIUM_GATE_RELEASE_COMMAND = "*8*20*20##"

PEDESTRIAN_DOOR_PRESS_COMMAND = "*8*19*21##"
PEDESTRIAN_DOOR_RELEASE_COMMAND = "*8*20*21##"
